stages:
  - build
  - push

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  IMAGE_TAG: $CI_COMMIT_REF_SLUG
  CI_REGISTRY: gitlab.ch:5050

before_script:
  # Логинимся в GitLab Container Registry
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

build_image:
  stage: build
  tags:
    - shell
  script:
    - pwd # чтобы увидеть текущую директорию
    - ls # чтобы увидеть список файлов
    - docker build --cache-from $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:$IMAGE_TAG apps/nginx/.
    # - docker tag nginx-image:latest ${CI_REGISTRY_IMAGE}:latest
  artifacts:
    paths:
      - Dockerfile
    expire_in: 1 hour

push_image:
  stage: push
  tags:
    - shell
  script:
    - docker push $IMAGE_NAME:$IMAGE_TAG
  only: 
    refs:
      - main
      - master
      - tags
  dependencies:
    - build_image