# настройка docker socket
# /etc/gitlab-runner/config.toml
# [[runners]]
#      executor = "docker"
#      [runners.docker]
#        privileged = true
#        volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
# sudo systemctl restart gitlab-runner

stages:
  - build

build_docker_image:
  stage: build
  tags:
    - docker        # Укажите тег Runner'а
  script:
    - docker build -t nginx-image:latest ./nginx/
    - docker tag nginx-image:latest ${CI_REGISTRY_IMAGE}:latest
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "${CI_REGISTRY}"
    - docker push ${CI_REGISTRY_IMAGE}:latest