stages:
  - build

build_docker_image:
  stage: build
  tags:
    - shell       # Укажите тег Runner'а
  script:
  - pwd  # Вывод текущей директории
  - ls   # Вывод списка файлов для проверки
  - docker build -t nginx-image:latest apps/nginx/.  # Сборка Docker-образа
  - echo "CI Registry Image: ${CI_REGISTRY_IMAGE}"  # Проверка значения переменной CI_REGISTRY_IMAGE
  - if [ -z "${CI_REGISTRY_IMAGE}" ]; then echo "CI_REGISTRY_IMAGE is empty"; exit 1; fi  # Проверка на пустое значение
  - docker tag nginx-image:latest ${CI_REGISTRY_IMAGE}:latest  # Тегирование образа
  - echo "Logging in to Docker registry..."  # Сообщение о начале входа
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "${CI_REGISTRY}"  # Вход в реестр
  - echo "Pushing image to registry..."  # Сообщение о начале отправки
  - docker push ${CI_REGISTRY_IMAGE}:latest  # Отправка образа в реестр