stages:
  - build
  - push

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  IMAGE_TAG: $CI_COMMIT_REF_SLUG

before_script:
  # Логинимся в GitLab Container Registry
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY


build_image:
  stage: build
  tags:
    - shell
  script:
    - pwd # чтобы увидеть текущую директорию
    - ls # чтобы увидеть список файлов
    - docker build -t nginx-image:latest apps/nginx/.
    # - docker tag nginx-image:latest ${CI_REGISTRY_IMAGE}:latest

push_image:
  stage: push
  tags:
    - shell
  script:
    - docker push $IMAGE_NAME:$IMAGE_TAG
  only: 
    refs:
      - main
      - master
      - tags
  dependencies:
    - build_image