stages:
  - build

build_docker_image:
  stage: build
  tags:
    - shell       # Укажите тег Runner'а
  script:
    - pwd # чтобы увидеть текущую директорию
    - ls # чтобы увидеть список файлов
    - docker build -t nginx-image:latest apps/nginx/.
    # - env # вывести все переменные для отладки
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "${CI_REGISTRY}"
    # - docker tag nginx-image:latest ${CI_REGISTRY_IMAGE}:latest
    # - docker push ${CI_REGISTRY_IMAGE}:latest